'use strict'

const { sql, poolPromise } = require('../db')

class annualProgress {
  static async getAll() {
    try {
      const pool = await poolPromise
      return await pool.request()
        .query(`SELECT NF.CLI, CLI.RASSOC, CLI.RESUMO, NF.ESTADO, CLI.REGIAO, NF.NUMERO, CONVERT(DATE,NF.EMI, 102) AS DT_FATURADO, 
        INF.QTD AS QTD_NF, INF.TOT, INF.CT_ICMS,INF.CT_PIS,INF.CT_COFINS,INF.CT_IPI,INF.CT_STICMS, 
        (INF.TOT-INF.CT_ICMS-INF.CT_PIS-INF.CT_COFINS) AS LIQUIDO , (INF.TOT+INF.CT_IPI+INF.CT_STICMS) AS BRUTO, INF.PECA AS PRODUTO, INF.DES AS DESCRICAO, 
        PED.CODIGO_FORNECEDOR AS COD_REPRESEN, F.RASSOC AS RASSOCFOR, 
        CASE
            WHEN FAMI.GRUPO = '30000' THEN 'SUCATA'
            ELSE FAMI.DESGRUPO
            END AS FAMILIA,
          CASE
            WHEN GRU.CODIGO = '10010' THEN '4 BOCAS'
            WHEN GRU.CODIGO = '10020' THEN '5 BOCAS'
            WHEN GRU.CODIGO = '10030' THEN '6 BOCAS'
            WHEN GRU.CODIGO = '10040' THEN 'LENHA'
            WHEN GRU.CODIGO = '10050' THEN 'COOKTOP'
            WHEN GRU.CODIGO = '10060' THEN 'FORNO ELET'
            ELSE GRU.DESCRICAO
            END AS CATEGORIA,
          CASE
            WHEN EST.DESCRI LIKE '%SIRIUS%' THEN 'SIRIUS'
            WHEN EST.DESCRI LIKE '%TOP GLASS%' THEN 'TOP GLASS'
            WHEN EST.DESCRI LIKE '%HORUS%' THEN 'HORUS'
            WHEN EST.DESCRI LIKE '%FENIX%' THEN 'FENIX'
            WHEN EST.DESCRI LIKE '%ASIATICO%' THEN 'ASIATICO'
            WHEN EST.DESCRI LIKE '%COOKTOP%' THEN 'COOKTOP'
            WHEN EST.DESCRI LIKE '%LENHA%' THEN 'LENHA'
            WHEN EST.DESCRI LIKE '%MASTER GLASS%' THEN 'MASTER GLASS'
            WHEN EST.DESCRI LIKE '%FORNO%' THEN 'FORNO'
            WHEN EST.DESCRI LIKE '%SUCATA%' THEN 'SUCATA'
            WHEN INF.PECA BETWEEN '12010001' AND '3000000' THEN 'PEÇAS'
            ELSE EST.DESCRI
            END AS MODELO,
          CASE
            WHEN EST.DESCRI LIKE '%SUCATA%' THEN 'SUCATA'
            WHEN NF.USUARIO IN ('INTEGRACAO','ALEXANDRA', 'TAINE') THEN 'E-COMMERCE'
            WHEN NF.USUARIO = 'JEAN' AND PED.DT_EMISSAO < '20211001' THEN 'E-COMMERCE'
            WHEN NF.USUARIO = 'NICOLAS' AND PED.DT_EMISSAO < '20210405' THEN 'E-COMMERCE'
            WHEN PED.CODIGO_FORNECEDOR IN ('F06169', 'F07154') THEN 'ASSISTENCIA BRASLAR'
            WHEN PED.CODIGO_FORNECEDOR IN ('F06195', 'F06210') THEN 'DIRETAS BRASLAR'
            ELSE 'VENDAS REPRESENTANTES'
            END AS TIPO_VENDA,
        CFOP.DESCRICAO AS NOME_CFOP, TCFOP.DESCRICAO AS TIPO_CFOP
        FROM BRASLAR_26.DBO.ITENNOTA AS INF
        LEFT JOIN BRASLAR_26.DBO.NOTAFISC AS NF ON (NF.NOTA = INF.NOTA)
        LEFT JOIN BRASLAR_26.DBO.CLIENTES AS CLI ON (CLI.CODIGO = NF.CLI)
        LEFT JOIN BRASLAR_26.DBO.CRM_PEDIDO AS PED ON (PED.PEDIDO = INF.NUMPED)
        LEFT JOIN BRASLAR_26.DBO.FORNECED AS F ON (F.CODIGO = PED.CODIGO_FORNECEDOR)
        --INCLUSÃO DE TABELA CFOP
        LEFT JOIN BRASLAR_26.DBO.CT_NOME_CFOP NCFOP ON (INF.CFOP = NCFOP.CFOP)
        LEFT JOIN BRASLAR_26.DBO.ESTOQUE EST ON (EST.CODIGO = INF.PECA)
        LEFT JOIN BRASLAR_26.DBO.GRUPOE FAMI ON (FAMI.GRUPO = EST.FAMILIA)
        LEFT JOIN BRASLAR_26.DBO.GRUPO_EST GRU ON (GRU.CODIGO = EST.CODGRUPO)
        LEFT JOIN BRASLAR_26.DBO.CT_NOME_CFOP CFOP ON (CFOP.CFOP = NF.CFOP)
        LEFT JOIN BRASLAR_26.DBO.CT_TIPOS_CFOP TCFOP ON (TCFOP.CODIGO = CFOP.TIPO_CFOP)
        WHERE NF.SITUACAO = 'IMPRESSA'
        AND YEAR(NF.EMI) = YEAR(GETDATE())
        AND GRU.CODIGO IN ('10010','10020','10030','10040','10050','10060')`)
    } catch (err) {
      console.log(err)
    }
  }
}

module.exports = annualProgress
