'use strict'

const { sql, poolPromise } = require('../db')

class topService {
  static async getAll() {
    try {
      const pool = await poolPromise
      return await pool.request().query(
        `SELECT TOP 10 NF.CLI, CLI.RASSOC, CLI.RESUMO, NF.ESTADO, CLI.REGIAO,
        SUM(INF.QTD) AS QTD_NF, SUM(INF.TOT) AS TOT, 
        SUM(INF.CT_ICMS) AS CT_ICMS,SUM(INF.CT_PIS) AS CT_PIS,SUM(INF.CT_COFINS) AS CT_COFINS,SUM(INF.CT_IPI) AS CT_IPI,SUM(INF.CT_STICMS) AS CT_STICMS, 
            (SUM(INF.TOT)-SUM(INF.CT_ICMS)-SUM(INF.CT_PIS)-SUM(INF.CT_COFINS)) AS LIQUIDO , 
        (SUM(INF.TOT)+SUM(INF.CT_IPI)+SUM(INF.CT_STICMS)) AS BRUTO 
            FROM BRASLAR_26.DBO.ITENNOTA AS INF
            LEFT JOIN BRASLAR_26.DBO.NOTAFISC AS NF ON (NF.NOTA = INF.NOTA)
            LEFT JOIN BRASLAR_26.DBO.CLIENTES AS CLI ON (CLI.CODIGO = NF.CLI)
            LEFT JOIN BRASLAR_26.DBO.CRM_PEDIDO AS PED ON (PED.PEDIDO = INF.NUMPED)
            LEFT JOIN BRASLAR_26.DBO.FORNECED AS F ON (F.CODIGO = PED.CODIGO_FORNECEDOR)
            --INCLUSÃO DE TABELA CFOP
            LEFT JOIN BRASLAR_26.DBO.CT_NOME_CFOP NCFOP ON (INF.CFOP = NCFOP.CFOP)
            LEFT JOIN BRASLAR_26.DBO.ESTOQUE EST ON (EST.CODIGO = INF.PECA)
            LEFT JOIN BRASLAR_26.DBO.GRUPOE FAMI ON (FAMI.GRUPO = EST.FAMILIA)
            LEFT JOIN BRASLAR_26.DBO.GRUPO_EST GRU ON (GRU.CODIGO = EST.CODGRUPO)
            LEFT JOIN BRASLAR_26.DBO.CT_NOME_CFOP CFOP ON (CFOP.CFOP = NF.CFOP)
            LEFT JOIN BRASLAR_26.DBO.CT_TIPOS_CFOP TCFOP ON (TCFOP.CODIGO = CFOP.TIPO_CFOP)
            WHERE NF.SITUACAO = 'IMPRESSA'
            AND NF.EMI >=GETDATE()-30
            AND GRU.CODIGO IN ('10010','10020','10030','10040','10050','10060')
    GROUP BY NF.CLI, CLI.RASSOC, CLI.RESUMO, NF.ESTADO, CLI.REGIAO
    ORDER BY SUM(INF.TOT) DESC`
      )
    } catch (err) {
      console.log(err)
    }
  }
}

module.exports = topService
